# Trovo gli scarti minimi in angoli_validi_step1_from0

In [1]:
import numpy as np

## Lettura dei dati

In [2]:
# PRIMA parte dei dati
data = np.loadtxt('data_to_180/con_prominence/angoli_validi_step1_from0_to110.txt', skiprows=1)
scarti1 = data[:, 3]
minimo1 = 10000
secondo_minimo1 = 10000
terzo_minimo1 = 10000

# prima devo cercare il minimo
for i, scarto in enumerate(scarti1):
    if scarto < minimo1:
        terzo_minimo1 = secondo_minimo1
        secondo_minimo1 = minimo1
        minimo1 = scarto

# poi devo andare a vedere quante volte in realtà compare quel minimo
indici_minimi_1 = [i for i, scarto in enumerate(scarti1) if scarto == minimo1]
indici_secondi_minimi_1 = [i for i, scarto in enumerate(scarti1) if scarto == secondo_minimo1]
indici_terzi_minimi_1 = [i for i, scarto in enumerate(scarti1) if scarto == terzo_minimo1]

# quindi trattengo solo gli scarti minimi
scarti_minimi_1 = scarti1[indici_minimi_1]
scarti_secondi_minimi_1 = scarti1[indici_secondi_minimi_1]
scarti_terzi_minimi_1 = scarti1[indici_terzi_minimi_1]

# e salvo le terne di angoli corrispondenti
angoli_minimi_1 = np.column_stack([
    data[indici_minimi_1, 0],
    data[indici_minimi_1, 1],
    data[indici_minimi_1, 2],
])

angoli_secondi_minimi_1 = np.column_stack([
    data[indici_secondi_minimi_1, 0],
    data[indici_secondi_minimi_1, 1],
    data[indici_secondi_minimi_1, 2],
])

angoli_terzi_minimi_1 = np.column_stack([
    data[indici_terzi_minimi_1, 0],
    data[indici_terzi_minimi_1, 1],
    data[indici_terzi_minimi_1, 2],
])

# libero la memoria
del data

# SECONDA PARTE DEI DATI - il minimo sta di là!
data = np.loadtxt('data_to_180/con_prominence/angoli_validi_step1_from110_to180.txt', skiprows=1, usecols=range(4))
scarti2 = data[:, 3]
minimo2 = 10000
secondo_minimo2 = 10000
terzo_minimo2 = 10000

# prima devo cercare il minimo
for i, scarto in enumerate(scarti2):
    if scarto < minimo2:
        terzo_minimo2 = secondo_minimo2
        secondo_minimo2 = minimo2
        minimo2 = scarto

# poi devo andare a vedere quante volte in realtà compare quel minimo
indici_minimi_2 = [i for i, scarto in enumerate(scarti2) if scarto == minimo2]
indici_secondi_minimi_2 = [i for i, scarto in enumerate(scarti2) if scarto == secondo_minimo2]
indici_terzi_minimi_2 = [i for i, scarto in enumerate(scarti2) if scarto == terzo_minimo2]

# quindi trattengo solo gli scarti minimi
scarti_minimi_2 = scarti2[indici_minimi_2]
scarti_secondi_minimi_2 = scarti2[indici_secondi_minimi_2]
scarti_terzi_minimi_2 = scarti2[indici_terzi_minimi_2]

# e salvo le terne di angoli corrispondenti
angoli_minimi_2 = np.column_stack([
    data[indici_minimi_2, 0],
    data[indici_minimi_2, 1],
    data[indici_minimi_2, 2],
])

angoli_secondi_minimi_2 = np.column_stack([
    data[indici_secondi_minimi_2, 0],
    data[indici_secondi_minimi_2, 1],
    data[indici_secondi_minimi_2, 2],
])

angoli_terzi_minimi_2 = np.column_stack([
    data[indici_terzi_minimi_2, 0],
    data[indici_terzi_minimi_2, 1],
    data[indici_terzi_minimi_2, 2],
])

# libero la memoria
del data

### Controllo da che parte sta il minimo

#### primo minimo

In [3]:
if minimo1 < minimo2:
    print("Il minimo sta tra 0 e 110")
elif minimo1 == minimo2:
    print("C'è un minimo in entrambe le regioni")
elif minimo1 > minimo2:
    print("Il minimo sta tra 110 e 180")

C'è un minimo in entrambe le regioni


#### secondo minimo

In [4]:
if secondo_minimo1 < secondo_minimo2:
    print(f"Il secondo minimo sta tra 0 e 110 ed è {secondo_minimo1}")
elif secondo_minimo1 == secondo_minimo2:
    print(f"C'è un secondo minimo in entrambe le regioni ed è {secondo_minimo1}")
elif secondo_minimo1 > secondo_minimo2:
    print(f"Il secondo minimo sta tra 110 e 180 ed è {secondo_minimo2}")

Il secondo minimo sta tra 110 e 180 ed è 0.037677629


#### terzo minimo

In [5]:
if terzo_minimo1 < terzo_minimo2:
    print(f"Il terzo minimo sta tra 0 e 110 ed è {terzo_minimo1}")
elif terzo_minimo1 == terzo_minimo2:
    print(f"C'è un terzo minimo in entrambe le regioni ed è {terzo_minimo1}")
elif terzo_minimo1 > terzo_minimo2:
    print(f"Il terzo minimo sta tra 110 e 180 ed è {terzo_minimo2}")

Il terzo minimo sta tra 110 e 180 ed è 0.038028358


In [10]:
# vediamo quanti sono i minimi
print('primi', len(indici_minimi_1), len(indici_minimi_2))
print('secondi', len(indici_secondi_minimi_1), len(indici_secondi_minimi_2))
print('terzi', len(indici_terzi_minimi_1), len(indici_terzi_minimi_2))

primi 620 300
secondi 4 2
terzi 1 2


In [7]:
print(angoli_terzi_minimi_1)

[[ 0. 27. 20.]]


In [8]:
print(angoli_terzi_minimi_2)

[[110.  25.  62.]
 [110.  25. 152.]]


In [11]:
angoli_minimi_2

array([[110.,  66.,  11.],
       [110.,  66.,  79.],
       [110.,  66., 101.],
       [110.,  66., 169.],
       [110., 114.,  11.],
       [110., 114.,  79.],
       [110., 114., 101.],
       [110., 114., 169.],
       [111.,  66.,  11.],
       [111.,  66.,  79.],
       [111.,  66., 101.],
       [111.,  66., 169.],
       [111., 114.,  11.],
       [111., 114.,  79.],
       [111., 114., 101.],
       [111., 114., 169.],
       [112.,  66.,  11.],
       [112.,  66.,  79.],
       [112.,  66., 101.],
       [112.,  66., 169.],
       [112., 114.,  11.],
       [112., 114.,  79.],
       [112., 114., 101.],
       [112., 114., 169.],
       [113.,  66.,  11.],
       [113.,  66.,  79.],
       [113.,  66., 101.],
       [113.,  66., 169.],
       [113., 114.,  11.],
       [113., 114.,  79.],
       [113., 114., 101.],
       [113., 114., 169.],
       [114.,  66.,  11.],
       [114.,  66.,  79.],
       [114.,  66., 101.],
       [114.,  66., 169.],
       [114., 114.,  11.],
 