# Trovo gli scarti minimi in angoli_validi_step1_from0

In [14]:
import numpy as np

## Lettura dei dati

In [ ]:
# PRIMA parte dei dati
data = np.loadtxt('data_to_180/senza_prominence/angoli_validi_step1_from0_to110.txt', skiprows=1)
scarti1 = data[:, 3]
minimo1 = 10000
secondo_minimo1 = 10000
terzo_minimo1 = 10000

# prima devo cercare il minimo
for i, scarto in enumerate(scarti1):
    if scarto < minimo1:
        terzo_minimo1 = secondo_minimo1
        secondo_minimo1 = minimo1
        minimo1 = scarto

# poi devo andare a vedere quante volte in realtà compare quel minimo
indici_minimi_1 = [i for i, scarto in enumerate(scarti1) if scarto == minimo1]
indici_secondi_minimi_1 = [i for i, scarto in enumerate(scarti1) if scarto == secondo_minimo1]
indici_terzi_minimi_1 = [i for i, scarto in enumerate(scarti1) if scarto == terzo_minimo1]

# quindi trattengo solo gli scarti minimi
scarti_minimi_1 = scarti1[indici_minimi_1]
scarti_secondi_minimi_1 = scarti1[indici_secondi_minimi_1]
scarti_terzi_minimi_1 = scarti1[indici_terzi_minimi_1]

# e salvo le terne di angoli corrispondenti
angoli_minimi_1 = np.column_stack([
    data[indici_minimi_1, 0],
    data[indici_minimi_1, 1],
    data[indici_minimi_1, 2],
])

angoli_secondi_minimi_1 = np.column_stack([
    data[indici_secondi_minimi_1, 0],
    data[indici_secondi_minimi_1, 1],
    data[indici_secondi_minimi_1, 2],
])

angoli_terzi_minimi_1 = np.column_stack([
    data[indici_terzi_minimi_1, 0],
    data[indici_terzi_minimi_1, 1],
    data[indici_terzi_minimi_1, 2],
])

# libero la memoria
del data

# SECONDA PARTE DEI DATI - il minimo sta di là!
data = np.loadtxt('data_to_180/senza_prominence/angoli_validi_step1_from110_to180.txt', skiprows=1, usecols=range(4))
scarti2 = data[:, 3]
minimo2 = 10000
secondo_minimo2 = 10000
terzo_minimo2 = 10000

# prima devo cercare il minimo
for i, scarto in enumerate(scarti2):
    if scarto < minimo2:
        terzo_minimo2 = secondo_minimo2
        secondo_minimo2 = minimo2
        minimo2 = scarto

# poi devo andare a vedere quante volte in realtà compare quel minimo
indici_minimi_2 = [i for i, scarto in enumerate(scarti2) if scarto == minimo2]
indici_secondi_minimi_2 = [i for i, scarto in enumerate(scarti2) if scarto == secondo_minimo2]
indici_terzi_minimi_2 = [i for i, scarto in enumerate(scarti2) if scarto == terzo_minimo2]

# quindi trattengo solo gli scarti minimi
scarti_minimi_2 = scarti2[indici_minimi_2]
scarti_secondi_minimi_2 = scarti2[indici_secondi_minimi_2]
scarti_terzi_minimi_2 = scarti2[indici_terzi_minimi_2]

# e salvo le terne di angoli corrispondenti
angoli_minimi_2 = np.column_stack([
    data[indici_minimi_2, 0],
    data[indici_minimi_2, 1],
    data[indici_minimi_2, 2],
])

angoli_secondi_minimi_2 = np.column_stack([
    data[indici_secondi_minimi_2, 0],
    data[indici_secondi_minimi_2, 1],
    data[indici_secondi_minimi_2, 2],
])

angoli_terzi_minimi_2 = np.column_stack([
    data[indici_terzi_minimi_2, 0],
    data[indici_terzi_minimi_2, 1],
    data[indici_terzi_minimi_2, 2],
])

# libero la memoria
del data

### Controllo da che parte sta il minimo

#### primo minimo

In [16]:
if minimo1 < minimo2:
    print("Il minimo sta tra 0 e 110")
elif minimo1 == minimo2:
    print("C'è un minimo in entrambe le regioni")
elif minimo1 > minimo2:
    print("Il minimo sta tra 110 e 180")

Il minimo sta tra 0 e 110


#### secondo minimo

In [17]:
if secondo_minimo1 < secondo_minimo2:
    print(f"Il secondo minimo sta tra 0 e 110 ed è {secondo_minimo1}")
elif secondo_minimo1 == secondo_minimo2:
    print(f"C'è un secondo minimo in entrambe le regioni ed è {secondo_minimo1}")
elif secondo_minimo1 > secondo_minimo2:
    print(f"Il secondo minimo sta tra 110 e 180 ed è {secondo_minimo2}")

Il secondo minimo sta tra 110 e 180 ed è 0.01571


#### terzo minimo

In [18]:
if terzo_minimo1 < terzo_minimo2:
    print(f"Il terzo minimo sta tra 0 e 110 ed è {terzo_minimo1}")
elif terzo_minimo1 == terzo_minimo2:
    print(f"C'è un terzo minimo in entrambe le regioni ed è {terzo_minimo1}")
elif terzo_minimo1 > terzo_minimo2:
    print(f"Il terzo minimo sta tra 110 e 180 ed è {terzo_minimo2}")

Il terzo minimo sta tra 110 e 180 ed è 0.0158139


In [19]:
# vediamo quanti sono i minimi
len(indici_terzi_minimi_1), len(indici_terzi_minimi_2)

(8, 16)

In [24]:
print(angoli_terzi_minimi_1)

[[  2.  76.  31.]
 [  2.  76. 121.]
 [  2. 104.  59.]
 [  2. 104. 149.]
 [  3.  76.  31.]
 [  3.  76. 121.]
 [  3. 104.  59.]
 [  3. 104. 149.]]


In [25]:
print(angoli_terzi_minimi_2)

[[110.  33.  63.]
 [110.  33. 153.]
 [110. 147.  27.]
 [110. 147. 117.]
 [111.  33.  63.]
 [111.  33. 153.]
 [111. 147.  27.]
 [111. 147. 117.]
 [112.  33.  63.]
 [112.  33. 153.]
 [112. 147.  27.]
 [112. 147. 117.]
 [113.  33.  63.]
 [113.  33. 153.]
 [113. 147.  27.]
 [113. 147. 117.]]


In [ ]:
anglesA =   [2.  76.  31.;
   2.  76. 121.;
   2. 104.  59.;
   2. 104. 149.;
   3.  76.  31.;
   3.  76. 121.;
   3. 104.  59.;
   3. 104. 149.];

anglesB = [110.  33.  63.;
 110.  33. 153.;
 110. 147.  27.;
 110. 147. 117.;
 111.  33.  63.;
 111.  33. 153.;
 111. 147.  27.;
 111. 147. 117.;
 112.  33.  63.;
 112.  33. 153.;
 112. 147.  27.;
 112. 147. 117.;
 113.  33.  63.;
 113.  33. 153.;
 113. 147.  27.;
 113. 147. 117.];